version: '3'
services:
  todosu:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - todosu-mysql
  todosu-mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=todos
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3306:3306
  todosu-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=todosu-mysql
      - PMA_PORT=3306
    